#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'marsExploration' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def marsExploration(s):
    # Write your code here
    suma = 0
    i = 0
    while i < len(s):
        if s[i] != 'S':
            suma+=1
        if s[i+1] != 'O':
            suma+=1
        if s[i+2] != 'S':
            suma+=1
        i+=3
    return suma
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = marsExploration(s)

    fptr.write(str(result) + '\n')

    fptr.close()
