#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'breakingRecords' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY scores as parameter.
#

def breakingRecords(scores):
    # Write your code here
    record = 0
    contador = 0
    recordmin =0
    contadormin=0
    for i in range(len(scores)):
        if record == 0 and i ==0:
            record = recordmin = scores[i]
        elif scores[i] > record:
            contador+=1
            record = scores[i]
        elif scores[i] < recordmin:
            contadormin +=1
            recordmin = scores[i]
    return contador, contadormin

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
