#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    # Write your code here
    maxi = 0
    mini = 0
    menos = sorted(arr)
    mas = sorted(arr, reverse=True)
    for i in range(4):
        maxi += mas[i]
        mini += menos[i]
        
    print(mini, maxi)
    

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
