#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    pos = 0
    neg = 0
    zer = 0
    tam = len(arr)
    for i in range(tam):
        if arr[i] > 0:
            
            pos+=1
            
        elif arr[i] < 0:
            neg+=1
        
            
        elif arr[i] == 0:
            zer+=1
            
    pos, neg, zer = pos/len(arr), neg/len(arr), zer/len(arr)
            
    print(f"{pos:.6f}\n{neg:.6f}\n{zer:.6f}\n")

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
